### ISSUE TITLE
Some troubles by starting of the sample

### ISSUE THREAD

**Issue by ivgg-me** [muuki88/e4GeminiJPA#14]
When I will start the sample from an _Eclipse for RCP and RAP Developers Luna Service Release 2 (4.4.2)_, I am getting following log and none of the used Entity Managers is injected:

```
!SESSION 2016-01-27 06:35:32.371 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_80
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=hu_HU
Framework arguments:  -product de.mukis.gemini.sample.rcp.product
Command-line arguments:  -product de.mukis.gemini.sample.rcp.product -data /home/ivgg/EclipseWorkspaces/RCP/e4GeminiJPA/../runtime-de.mukis.gemini.sample.product -dev file:/home/ivgg/EclipseWorkspaces/RCP/e4GeminiJPA/.metadata/.plugins/org.eclipse.pde.core/de.mukis.gemini.sample.product/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog

!ENTRY org.eclipse.equinox.ds 1 0 2016-01-27 06:35:35.006
!MESSAGE Could not bind a reference of component org.eclipse.gemini.ext.di.emf. The reference is: Reference[name = EntityManagerFactory, interface = javax.persistence.EntityManagerFactory, policy = dynamic, cardinality = 0..n, target = null, bind = bindEntityManagerFactory, unbind = unbindEntityManagerFactory]

!ENTRY org.eclipse.equinox.ds 1 0 2016-01-27 06:35:35.007
!MESSAGE Could not bind a reference of component org.eclipse.gemini.ext.di.emf. The reference is: Reference[name = EntityManagerFactoryBuilder, interface = org.osgi.service.jpa.EntityManagerFactoryBuilder, policy = dynamic, cardinality = 0..n, target = null, bind = bindEntityManagerFactoryBuilder, unbind = unbindEntityManagerFactoryBuilder]

!ENTRY org.eclipse.equinox.ds 1 0 2016-01-27 06:35:35.014
!MESSAGE Could not bind a reference of component org.eclipse.gemini.ext.di.em. The reference is: Reference[name = EntityManagerFactory, interface = javax.persistence.EntityManagerFactory, policy = dynamic, cardinality = 0..n, target = null, bind = bindEntityManagerFactory, unbind = unbindEntityManagerFactory]

!ENTRY org.eclipse.equinox.ds 1 0 2016-01-27 06:35:35.015
!MESSAGE Could not bind a reference of component org.eclipse.gemini.ext.di.em. The reference is: Reference[name = EntityManagerFactoryBuilder, interface = org.osgi.service.jpa.EntityManagerFactoryBuilder, policy = dynamic, cardinality = 0..n, target = null, bind = bindEntityManagerFactoryBuilder, unbind = unbindEntityManagerFactoryBuilder]
[GEMINI_EXT][ERROR][GeminiEMSupplier] EntityManagerFactoryBuilder is null for unit 'configured' with properties {}
[GEMINI_EXT][ERROR][GeminiEMSupplier] EntityManagerFactoryBuilder is null for unit 'unconfigured' with properties {eclipselink.weaving=false, javax.persistence.jdbc.url=jdbc:derby:memory:test2;create=true, eclipselink.ddl-generation.output-mode=database, eclipselink.logging.level=FINE, eclipselink.ddl-generation=create-tables, javax.persistence.jdbc.driver=org.apache.derby.jdbc.EmbeddedDriver, eclipselink.weaving.internal=false}
[GEMINI_EXT][ERROR][GeminiEMFSupplier] EntityManagerFactoryBuilder is null for unit 'configured' with properties {}
```

I have following bundles installed in the Eclipse instance:
- AnyEditTools  2.6.0.201511291145  AnyEditTools.feature.group  Andrey Loskutov
- Apache Commons Collections    4.1.0   org.apache.commons.collections4 The Apache Software Foundation
- Apache Commons Lang   3.4.0   org.apache.commons.lang3    The Apache Software Foundation
- CollabNet Merge Client    4.1.0   com.collabnet.subversion.merge.feature.feature.group    CollabNet
- E4 Context Spy Feature (Incubation)   0.1.0.v20141107-1620    org.eclipse.e4.tools.context.spy.feature.feature.group  Eclipse.org
- E4 CSS Spy (Incubation)   0.14.0.v20140808-1908   org.eclipse.e4.tools.css.spy.feature.feature.group  Eclipse.org
- E4 CSS Spy (Incubation) Developer Resources   0.14.0.v20140808-1908   org.eclipse.e4.tools.css.spy.feature.source.feature.group   Eclipse.org
- E4 Event Spy (Incubation) 0.15.0.v20141107-1620   org.eclipse.e4.tools.event.spy.feature.feature.group    Eclipse.org
- E4 Event Spy (Incubation) Developer Resources 0.15.0.v20141107-1620   org.eclipse.e4.tools.event.spy.feature.source.feature.group Eclipse.org
- Eclipse 4 - All Spies (Incubation)    0.1.0.v20141219-1152    org.eclipse.e4.tools.spies.feature.feature.group    Eclipse.org
- Eclipse 4 - Model Spy (Incubation)    0.1.0.v20141219-1152    org.eclipse.e4.tools.model.spy.feature.feature.group    Eclipse.org
- Eclipse Checkstyle Plug-in    6.11.1.201510102004 net.sf.eclipsecs.feature.group  http://eclipse-cs.sf.net/
- Eclipse e4 Tools (Incubation) 0.14.0.v20150108-1540   org.eclipse.e4.core.tools.feature.feature.group Eclipse.org
- Eclipse e4 Tools Source (Incubation)  0.14.0.v20150108-1540   org.eclipse.e4.core.tools.feature.source.feature.group  Eclipse.org
- Eclipse for RCP and RAP Developers    4.4.2.20150219-0708 epp.package.rcp null
- Eclipse Git Team Provider 4.1.1.201511131810-r    org.eclipse.egit.feature.group  Eclipse EGit
- **EclipseLink Target Components   2.4.0.v20120613-r11652  org.eclipse.persistence.sdk.feature.group   Eclipse.org - EclipseLink Project**
- FindBugs Feature  3.0.1.20150306-5afe4d1  edu.umd.cs.findbugs.plugin.eclipse.feature.group    FindBugs Project
- **Gemini DBAccess for Derby   1.1.0.RELEASE   org.eclipse.gemini.dbaccess.feature.feature.group   Eclipse Gemini DBAccess**
- **Gemini DBAccess for H2  1.1.0.RELEASE   org.eclipse.gemini.dbaccess.h2.feature.feature.group    Eclipse Gemini DBAccess**
- **Gemini DBAccess for MySQL   1.1.0.RELEASE   org.eclipse.gemini.dbaccess.mysql.feature.feature.group Eclipse Gemini DBAccess**
- **Gemini e4 DI    1.1.2.201308292016  org.eclipse.gemini.ext.di.feature.feature.group null**
- **Gemini JPA  1.1.0.RELEASE   org.eclipse.gemini.jpa.feature.feature.group    Oracle Corp.**
- Gemini JPA Samples    1.1.0.RELEASE   org.eclipse.gemini.jpa.samples.feature.feature.group    Oracle Corp.
- JAutodoc  1.13.0  net.sf.jautodoc.feature.feature.group   Martin Kesting
- Java implementation of Git    4.1.1.201511131810-r    org.eclipse.jgit.feature.group  Eclipse JGit
- **Oracle Corporation's JDBC Driver for MySQL  5.1.38  com.mysql.jdbc  Oracle Corporation**
- Subclipse (Required)  1.10.10 org.tigris.subversion.subclipse.feature.group   tigris.org
- Subclipse Integration for Mylyn 3.x (Optional)    3.0.0   org.tigris.subversion.subclipse.mylyn.feature.group tigris.org
- Subversion Client Adapter (Required)  1.10.3  org.tigris.subversion.clientadapter.feature.feature.group   tigris.org
- Subversion JavaHL Native Library Adapter  1.8.14  org.tigris.subversion.clientadapter.javahl.feature.feature.group    tigris.org
- Subversion Revision Graph 1.1.1   org.tigris.subversion.subclipse.graph.feature.feature.group tigris.org
- SVNKit Client Adapter (Not required)  1.8.9   org.tigris.subversion.clientadapter.svnkit.feature.feature.group    tigris.org
- SWT Designer Documentation    1.7.0.r44x201405030426  org.eclipse.wb.rcp.doc.user.feature.feature.group   Eclipse.org
- SWT Designer SWT_AWT Support  1.7.0.r44x201405021546  org.eclipse.wb.rcp.SWT_AWT_support.feature.group    Eclipse.org
- WindowBuilder Core Documentation  1.7.0.r44x201405021506  org.eclipse.wb.doc.user.feature.feature.group   Eclipse.org

When I will get this sample working with MySQL what I must do? What must I do to get an Entity Manager injected in my own project? 

Thanks for your help!

**Comment by muuki88** [comment]
Sorry, I'm not long maintainer GeminiJPA. You error looks like either a configuration error and a necessary bundle is missing (maybe the oracle driver doesn't expose jdbc correctly)
